--1
SELECT E.FIRST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, E.SALARY FROM HR.EMPLOYEES E JOIN HR.DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN HR.JOBS J ON E.JOB_ID=J.JOB_ID ORDER BY DEPARTMENT_NAME;

--2
SELECT D.DEPARTMENT_NAME FROM HR.DEPARTMENTS D JOIN HR.EMPLOYEES E 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID HAVING COUNT(E.EMPLOYEE_ID) >= 2 GROUP BY D.DEPARTMENT_NAME;

--3
SELECT * FROM HR.EMPLOYEES E JOIN HR.JOBS J ON E.JOB_ID = J.JOB_ID AND (J.MIN_SALARY >= E.SALARY);

--4
SELECT E.FIRST_NAME, E.JOB_ID, D.DEPARTMENT_NAME, L.STREET_ADDRESS, L.CITY 
FROM HR.EMPLOYEES E JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID JOIN HR.LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID AND L.STATE_PROVINCE = NULL;

--5
SELECT UNIQUE E.* FROM HR.EMPLOYEES E, HR.DEPARTMENTS D WHERE E.DEPARTMENT_ID IS NULL;