--Viva Question
SELECT (SALARY*12) as "ANNUAL_SALARY" FROM HR.EMPLOYEES

--Practice Questions
SELECT * FROM HR.EMPLOYEES WHERE (SALARY*12)>20000 AND (SALARY*12) < 30000;

SELECT EMPLOYEE_ID, FIRST_NAME FROM HR.EMPLOYEES WHERE DEPARTMENT_ID BETWEEN 60 AND 100

SELECT * FROM HR.LOCATIONS WHERE CITY IN ('Toronto', 'Hiroshima', 'Sydney')

SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE '%ll%'

SELECT * FROM HR.EMPLOYEES WHERE COMMISSION_PCT IS NULL


--TASKS (LAB 02)

--1
SELECT initcap(first_name) AS "First Name", LOWER(job_id) AS "Job I'd" FROM hr.employees;

--2
SELECT FIRST_NAME || JOB_ID AS "Name,JOB", LENGTH(FIRST_NAME) AS "LENGTH", INSTR(FIRST_NAME,'A') AS "NO. OF A'S" FROM HR.EMPLOYEES WHERE JOB_ID = 'IT_PROG'
--3


--4
SELECT EMPLOYEE_ID, HIRE_DATE, TO_CHAR(HIRE_DATE,'MONTH') AS "MONTH AS STRING" FROM HR.EMPLOYEES WHERE HIRE_DATE LIKE '%-03%'

--5
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'MM') AS "HIRE_MONTH",TO_CHAR(HIRE_DATE,'YYYY') AS "HIRE_YEAR" FROM HR.EMPLOYEES

--6
SELECT FIRST_NAME, HIRE_DATE FROM HR.EMPLOYEES WHERE TO_DATE(HIRE_DATE,'16-SEP-21')