--1
CREATE USER IBADULLAH IDENTIFIED BY ABC1234
GRANT CONNECT, RESOURCE, DBA TO IBADULLAH

--2
CREATE TABLE  JOBS
(
    JOB_ID VARCHAR(10) NOT NULL PRIMARY KEY, 
    JOB_TITLE VARCHAR(30), 
    MIN_SALARY NUMBER, 
    MAX_SALARY NUMBER 
)
SELECT * FROM JOBS

CREATE TABLE  JOB_HISTORY
(
    JOB_ID VARCHAR(10) NOT NULL PRIMARY KEY, 
    START_DATE DATE, 
    END_DATE DATE, 
    EMPLOYEE_ID NUMBER, 
    DEPARTMENT_ID NUMBER 
);
SELECT * FROM JOB_HISTORY

--3
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID)

--4
INSERT INTO JOBS VALUES(1, 'DIRECTOR', 10000, 50000)

--5
INSERT INTO JOB_HISTORY VALUES (1, '21-APR-02', '02-OCT-61', 123, 456)

--6
ALTER TABLE JOBS MODIFY JOB_ID NUMBER(10)

--7
ALTER TABLE JOBS ADD (JOB_NATURE VARCHAR(30))

--8
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES WHERE 1=2

--9
ALTER TABLE JOBS DROP COLUMN JOB_NATURE

--10
