--1, 2, 4, 5 & 6 were done in Lab.
--Remaining are here in this submission.

--3
SELECT EMPLOYEE_ID, HIRE_DATE, ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE),0) AS "Months Employeed",
NEXT_DAY(HIRE_DATE,'FRIDAY') AS "NEXT FRIDAY", LAST_DAY(HIRE_DATE)"LAST DAY" FROM HR.EMPLOYEES;

--7
SELECT SALARY, FIRST_NAME FROM HR.EMPLOYEES WHERE FIRST_NAME='Steven' AND 
TO_CHAR(SALARY,'$9999')

--8
SELECT NEXT_DAY(SYSDATE,'Monday') AS "Next Monday From Current Date" FROM DUAL

--9
SELECT * FROM HR.EMPLOYEES WHERE LAST_NAME LIKE '%A%'

--10
SELECT SUBSTR(FIRST_NAME,-3,3) AS "Last three Letters" FROM HR.EMPLOYEES

--11
SELECT EMPLOYEE_ID, FIRST_NAME, (SALARY+(SALARY*0.15)) AS "Incremented Salaray",
(SALARY*0.15) AS "Incremented Amount" FROM HR.EMPLOYEES

--12
SELECT FIRST_NAME, HIRE_DATE, TO_CHAR(HIRE_DATE,'day') AS "DAY" FROM HR.EMPLOYEES
ORDER BY MOD (TO_CHAR(HIRE_DATE,'D')+5,7)

--13
SELECT DEPARTMENT_ID, MANAGER_ID, ROUND(AVG(COMMISSION_PCT),1) AS "Average" FROM 
HR.EMPLOYEES GROUP BY DEPARTMENT_ID, MANAGER_ID