--6
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM HR.EMPLOYEES 
WHERE JOB_ID IN(SELECT JOB_ID FROM HR.EMPLOYEES WHERE LAST_NAME='Taylor');

--7
UPDATE HR.JOBS SET MIN_SALARY = MIN_SALARY + (MIN_SALARY *0.2) WHERE MIN_SALARY=6000;

--8
CREATE TABLE EMPLOYEE_BKP AS SELECT * FROM HR.EMPLOYEES WHERE 1=2;

INSERT INTO EMPLOYEE_BKP SELECT * FROM HR.EMPLOYEES WHERE HIRE_DATE IN (SELECT HIRE_DATE FROM HR.EMPLOYEES 
WHERE HIRE_DATE = '13-JAN-01'); 

--9
DELETE FROM EMPLOYEE_BKP WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE_BKP 
WHERE JOB_ID = 'FI_ACCOUNT' AND MANAGER_ID IS NOT NULL);